language: go
sudo: false

go:
- 1.12.x

before_install:
  - wget https://github.com/golang/dep/releases/download/v0.3.2/dep-linux-amd64 -O $HOME/gopath/bin/dep
  - chmod u+x $HOME/gopath/bin/dep

install:
  - dep ensure

script:
  - go test